In [1]:
#python notebook - python
a=5
b=5

In [4]:
c=a+b

In [5]:
c

10

In [6]:
# Linear Regression
dataset = 'https://raw.githubusercontent.com/VishnuvarshanP/LinearRegression/main/Advertising.csv'

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv(dataset)

In [9]:
df.head() #first 5 rows

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [10]:
df.tail() #last 5 rows

Unnamed: 0     TV  radio  newspaper  sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [11]:
df = pd.read_csv('/content/weight-height.csv')

In [12]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [16]:
df.drop('Gender',axis=1,inplace=True) # axis = 0 is row and axis = 1 is column

In [17]:
df.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [19]:
x=df[['Height']] #input
y=df[['Weight']] #expected output

In [20]:
x

Height
0     73.847017
1     68.781904
2     74.110105
3     71.730978
4     69.881796
...         ...
9995  66.172652
9996  67.067155
9997  63.867992
9998  69.034243
9999  61.944246

[10000 rows x 1 columns]

In [21]:
y

Weight
0     241.893563
1     162.310473
2     212.740856
3     220.042470
4     206.349801
...          ...
9995  136.777454
9996  170.867906
9997  128.475319
9998  163.852461
9999  113.649103

[10000 rows x 1 columns]

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
model = LinearRegression()

In [24]:
model.fit(x,y)

LinearRegression()

In [25]:
model.coef_ #m = slope value

array([[7.71728764]])

In [26]:
model.intercept_ # c = intercept

array([-350.73719181])

In [27]:
model.predict([[84.5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[301.37361383]])

In [28]:
model.predict([[90]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[343.81869586]])

In [29]:
import pickle

In [30]:
pickle.dump(model,open('model.sav','wb'))

In [31]:
#accuracy of the model
model.score(x,y)

0.8551742120609958

In [32]:
#adjusted r^2
n = x.shape[0] # 0 = row
p = x.shape[1] #1 = column
r2 = model.score(x,y)
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)

In [33]:
adjusted_r2

0.8551597265851066